sudo: false

branches:
  except:
    - gh-pages

os: linux
dist: trusty

language: cpp
compiler: gcc

jobs:
  include:
    - stage: make-and-test
      os: linux
      compiler: gcc
      env:
      - BUILD_TYPE='Debug'
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
            - doxygen-doc 
            - doxygen-latex 
            - doxygen-gui 
            - graphviz
            - mathgl
            - libmgl-dev
            - liblapack-dev
            - libblas-dev
            - gfortran
      script: 
        - export CC=gcc-8 ;
        - export CXX=g++-8 ;
        # Check versions of gcc, g++ and cmake
        - gcc -v && g++ -v && cmake --version
        - ./tests.sh
    - stage: doxygen-doc
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: build/doc/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
