language: cpp
compiler: gcc

sudo: false

branches:
  except:
    - gh-pages


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"

env:
  global:
    - GH_REPO_NAME: GraphLib
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile.in
    - GH_REPO_REF: github.com/guetzli32/GraphLib.git

addons:
  apt:
    packages:
      - doxygen-doc 
      - doxygen-latex 
      - doxygen-gui 
      - graphviz
      - mathgl
      - liblapack-dev
      - libblas-dev
      - gfortran

jobs:
  include:
    - stage: make
      script: ./make.sh
    - stage: test
      script: ./test/test.sh
    - stage: doxygen-doc
      script: doxygen doc/Doxyfile.in


deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
