sudo: false

branches:
  except:
    - gh-pages

os: linux
dist: trusty

language: cpp
compiler: gcc

env:
  global:
    - GH_REPO_NAME: GraphLib
    - DOXYFILE: $TRAVIS_BUILD_DIR/doc/Doxyfile.in
    - GH_REPO_REF: github.com/guetzli32/GraphLib.git

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - gcc-8
      - doxygen-doc 
      - doxygen-latex 
      - doxygen-gui 
      - graphviz
      - mathgl
      - liblapack-dev
      - libblas-dev
      - gfortran

jobs:
  include:
    - stage: make-and-test
      os: linux
      compiler: gcc
      env:
      - BUILD_TYPE='Debug'
      script: 
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            export CC=gcc-8 ;
            export CXX=g++-8 ;
          fi
        # Check versions of gcc, g++ and cmake
        - gcc -v && g++ -v && cmake --version
        - ./tests.sh
    - stage: doxygen-doc
      script: doxygen doc/Doxyfile.in

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
