sudo: true

branches:
  except:
    - gh-pages

os: linux
dist: trusty

language: cpp
compiler: gcc

cache:
  directories:
  - $TRAVIS_BUILD_DIR/dependencies

jobs:
  include:
    - stage: make-and-test
      os: linux
      compiler: gcc
      env:
      - BUILD_TYPE='Debug'
      - MAKEFLAGS='-j$(nproc)'
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - gcc-8
            - mathgl
            - libmgl-dev
            - liblapack-dev
            - libblas-dev
            - gfortran
      script: 
        - export CC=gcc-8 ;
        - export CXX=g++-8 ;
        - ./tests.sh
    - stage: doxygen
      os: linux
      compiler: gcc
      env:
      - MAKEFLAGS='-j$(nproc)'
      - DEPS_DIR=${TRAVIS_BUILD_DIR}/dependencies
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - doxygen
            - doxygen-doc
            - doxygen-gui
            - doxygen-latex
            - flex
            - bison
            - graphviz
      script:
        - export CXX=g++-8 ;
        - mkdir -p $TRAVIS_BUILD_DIR/doc/build
        - cd $TRAVIS_BUILD_DIR/doc/build
        - doxygen ../Doxyfile.in

      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: $TRAVIS_BUILD_DIR/doc/doc/html
        github_token: $GH_REPO_TOKEN
        on:
          branch: master
